on: push
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - run: pwd
      - run: ls -l
      - run: wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
      - run: ls -l
      - run: DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AZEOvhUj8Ks15qbekOENlFkOgKcDw0LX_pOaMkYLjXBrkC8IITTUdkix8Y8HeOtVda33mw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
